## Quiz 1 - Semana 5

In [3]:
from numpy.linalg import det, eig
from numpy import matmul
import numpy as np


In [4]:
def quiz(a, b, c, d, lista_l):

    A = np.array([[a, b],
                  [c, d]])

    lista_l_final = []

    for l in lista_l:

        L = np.array([[l, 0],
                      [0, l]])

        #print(f"Lâmbda {l} resulta em det = {det(A - L)}")
        if det(A - L) == 0:
            print(f"Lâmbda {l} resulta em det = {det(A - L)}")
            lista_l_final.append(l)
            print(A - L)

    return eig(A)

In [5]:
quiz(1, 0, 0, 2, [1, -1, 2, -2]),

Lâmbda 1 resulta em det = 0.0
[[0 0]
 [0 1]]
Lâmbda 2 resulta em det = 0.0
[[-1  0]
 [ 0  0]]


((array([1., 2.]),
  array([[1., 0.],
         [0., 1.]])),)

In [6]:
quiz(3, 4, 0, 5, [3, -3, 5, -5])

Lâmbda 3 resulta em det = 0.0
[[0 4]
 [0 2]]
Lâmbda 5 resulta em det = 0.0
[[-2  4]
 [ 0  0]]


(array([3., 5.]),
 array([[1.        , 0.89442719],
        [0.        , 0.4472136 ]]))

In [7]:
quiz(1, 0, -1, 4, [1, -1, 4, -4])

Lâmbda 1 resulta em det = 0.0
[[ 0  0]
 [-1  3]]
Lâmbda 4 resulta em det = 0.0
[[-3  0]
 [-1  0]]


(array([4., 1.]),
 array([[0.        , 0.9486833 ],
        [1.        , 0.31622777]]))

In [8]:
quiz(-3, 8, 2, 3, [5, -5])

Lâmbda 5 resulta em det = 0.0
[[-8  8]
 [ 2 -2]]
Lâmbda -5 resulta em det = 0.0
[[2 8]
 [2 8]]


(array([-5.,  5.]),
 array([[-0.9701425 , -0.70710678],
        [ 0.24253563, -0.70710678]]))

In [9]:
eig(np.array([[5, 4], [-4, -3]]))

(array([1.+2.98023224e-08j, 1.-2.98023224e-08j]),
 array([[ 0.70710678+0.00000000e+00j,  0.70710678-0.00000000e+00j],
        [-0.70710678+5.26835606e-09j, -0.70710678-5.26835606e-09j]]))

In [10]:
eig(np.array([[-2, -3], [1, 1]]))

(array([-0.5+0.8660254j, -0.5-0.8660254j]),
 array([[ 0.8660254+0.j  ,  0.8660254-0.j  ],
        [-0.4330127-0.25j, -0.4330127+0.25j]]))

## Quiz 2 - Semana 5

In [11]:
# Calcular a matriz diagonal 
# D = C^-1 * T * C

def matriz_diagonal(t11, t12, t21, t22, c11, c12, c21, c22):
    T = np.array([[t11, t12],
                  [t21, t22]])

    C = np.array([[c11, c12],
                  [c21, c22]])                  

    Cinv = np.linalg.inv(C)

    return np.matmul(np.matmul(Cinv, T), C)

In [12]:
# Q1
matriz_diagonal(6,-1,2,3,1,1,1,2)

array([[5., 0.],
       [0., 4.]])

In [13]:
# Q2
matriz_diagonal(2,7,0,-1,7,1,-3,0)

array([[-1.00000000e+00,  0.00000000e+00],
       [ 1.77635684e-15,  2.00000000e+00]])

In [14]:
# Q3
matriz_diagonal(1,0,2,-1,1,0,1,1)

array([[ 1.,  0.],
       [ 0., -1.]])

In [15]:
def matriz_potencial(c11, c12, c21, c22, d11, d12, d21, d22, power):
    C = np.array([[c11, c12],
                  [c21, c22]]) 

    D = np.array([[d11 ** power, d12],
                  [d21, d22 ** power]])

    Cinv = np.linalg.inv(C)

    T = np.matmul(np.matmul(C, D), Cinv)
    return T

In [16]:
# Q4
matriz_potencial(1,2,0,1,10,0,0,10, 1)

array([[10.,  0.],
       [ 0., 10.]])

In [17]:
# Q5
matriz_potencial(1,1,1,2,5,0,0,4,3)

array([[186., -61.],
       [122.,   3.]])

In [18]:
# Q6
matriz_potencial(7,1,-3,0,-1,0,0,2,3)

array([[ 8., 21.],
       [ 0., -1.]])

In [19]:
# Q7
matriz_potencial(1,0,1,1,1,0,0,-1,5)

array([[ 1.,  0.],
       [ 2., -1.]])

## Quiz 3

In [28]:
# Q4
A  = np.array([[0,1,0,0],
              [1,0,0,0],
              [0,1,0,0],
              [0,0,1,0]])

print(np.linalg.det(A))

vals, vecs = np.linalg.eig(A)           
vals, vecs.round(1)

0.0


(array([ 0.,  0.,  1., -1.]),
 array([[ 0. ,  0. ,  0.5,  0.5],
        [ 0. ,  0. ,  0.5, -0.5],
        [ 0. ,  0. ,  0.5,  0.5],
        [ 1. , -1. ,  0.5, -0.5]]))

In [33]:
# Q5
A  = np.array([[0,1,0,0],
              [1,0,0,0],
              [0,1,0,0],
              [0,0,1,0]])

D = np.array([[.1,.1,.1,.7],
              [.7,.1,.1,.1],
              [.1,.7,.1,.1],
              [.1,.1,.7,.1]])

B = D @ A
'''
while np.linalg.norm(A - B) > 0.01 :
    lastA = B
    B = L @ B
print(B)
'''
vals, vecs = np.linalg.eig(B)           
vals, vecs.round(1)

(array([ 0. ,  1. ,  0.6, -0.6]),
 array([[ 0. ,  0.5, -0.5,  0.7],
        [ 0. ,  0.5,  0.5, -0. ],
        [ 0. ,  0.5, -0.5, -0.7],
        [ 1. ,  0.5,  0.5, -0. ]]))

In [41]:
# Q6
a11 = 3/2
a12 = -1
a21 = -1/2
a22 = 1/2

print(f"lambda ^ 2 - {a11 + a22} * lambda + {a11 * a22 - a12 * a21} ")

lambda ^ 2 - 2.0 * lambda + 0.25 


In [46]:
# Q8
A = np.array([[3/2, -1],
              [-1/2, 1/2]])

print(np.linalg.eig(A))
3 ** (1/2)


(array([1.8660254, 0.1339746]), array([[ 0.9390708 ,  0.59069049],
       [-0.34372377,  0.80689822]]))


1.7320508075688772

## Pagerank

In [14]:
import numpy as np
import numpy.linalg as la

In [12]:
# Matrix de probabilidade para ir a cada página
L = np.array([[0,   1/2, 1/3, 0, 0,   0 ],
              [1/3, 0,   0,   0, 1/2, 0 ],
              [1/3, 1/2, 0,   1, 0,   1/2],
              [1/3, 0,   1/3, 0, 1/2, 1/2],
              [0,   0,   0,   0, 0,   0 ],
              [0,   0,   1/3, 0, 0,   0 ]])

In [24]:
# Resolução mais simples, porém mais custosa em termos de processamento.
eVals, eVecs = la.eig(L) # Gets the eigenvalues and vectors
print(f"Autovalores originais: {eVals.round(2)}")
print(f"Autovetores originais:\n{eVecs.round(2)}")

order = np.absolute(eVals).argsort()[::-1] # Orders them by their eigenvalues
print(f"Ordem de grandeza: {order}")

r = eVecs[:, 0] # Sets r to be the principal eigenvector
print(f"Principal autovetor: {r.round(2)}")

100 * np.real(r / np.sum(r)) # Make this eigenvector sum to one, then multiply by 100 Procrastinating Pats

Autovalores originais: [ 1.  +0.j   0.31+0.j  -0.54+0.3j -0.54-0.3j -0.23+0.j   0.  +0.j ]
Autovetores originais:
[[ 0.31+0.j    0.53+0.j   -0.25-0.36j -0.25+0.36j -0.29+0.j   -0.8 +0.j  ]
 [ 0.1 +0.j    0.56+0.j    0.03+0.23j  0.03-0.23j  0.43+0.j    0.  +0.j  ]
 [ 0.77+0.j   -0.34+0.j    0.7 +0.j    0.7 -0.j   -0.44+0.j   -0.  +0.j  ]
 [ 0.49+0.j   -0.38+0.j   -0.15+0.31j -0.15-0.31j -0.34+0.j    0.27+0.j  ]
 [ 0.  +0.j    0.  +0.j    0.  +0.j    0.  -0.j    0.  +0.j    0.53+0.j  ]
 [ 0.26+0.j   -0.37+0.j   -0.33-0.18j -0.33+0.18j  0.65+0.j   -0.  +0.j  ]]
Ordem de grandeza: [0 3 2 1 4 5]
Principal autovetor: [0.31+0.j 0.1 +0.j 0.77+0.j 0.49+0.j 0.  +0.j 0.26+0.j]


array([16.        ,  5.33333333, 40.        , 25.33333333,  0.        ,
       13.33333333])

## Quiz Final

In [1]:
import numpy as np

In [3]:
# Q1
A = np.array([[4,-5,6],
            [7,-8,6],
            [3/2,-1/2,-2]])

np.linalg.eig(A)     

(array([ 1., -4., -3.]),
 array([[-0.6882472 , -0.66666667,  0.40824829],
        [-0.6882472 , -0.66666667, -0.40824829],
        [-0.22941573,  0.33333333, -0.81649658]]))

In [40]:
# Q2
L = np.array([[0,0,0,1],
              [1,0,0,0],
              [0,1,0,0],
              [0,0,1,0]])

vals, vecs = np.linalg.eig(L)
print(f"Autovalores: {np.real(vals).round(2)}")

order = np.absolute(vals).argsort()[::-1]
order
#vecs = vecs[:,order]
np.real(vecs).round(2)

Autovalores: [-1.  0.  0.  1.]


array([[-0.5,  0. ,  0. , -0.5],
       [ 0.5, -0.5, -0.5, -0.5],
       [-0.5, -0. , -0. , -0.5],
       [ 0.5,  0.5,  0.5, -0.5]])

In [42]:
# Q3
L = np.array([[.1,.1,.1,.7],
              [.7,.1,.1,.1],
              [.1,.7,.1,.1],
              [.1,.1,.7,.1]])

vals, vecs = np.linalg.eig(L)
print(f"Autovalores: {np.real(vals).round(2)}")

order = np.absolute(vals).argsort()[::-1]
order
np.real(vecs).round(2)

Autovalores: [ 1.  -0.6  0.   0. ]


array([[ 0.5,  0.5,  0.5,  0.5],
       [ 0.5, -0.5, -0. , -0. ],
       [ 0.5,  0.5, -0.5, -0.5],
       [ 0.5, -0.5,  0. ,  0. ]])

In [45]:
#Q4
L = np.array([[0,1,0,0],
              [1,0,0,0],
              [0,0,0,1],
              [0,0,1,0]])
            
vals, vecs = np.linalg.eig(L)
print(f"Autovalores: {np.real(vals).round(2)}")

order = np.absolute(vals).argsort()[::-1]
order
np.real(vecs).round(2)

Autovalores: [ 1. -1.  1. -1.]


array([[ 0.71, -0.71,  0.  ,  0.  ],
       [ 0.71,  0.71,  0.  ,  0.  ],
       [ 0.  ,  0.  ,  0.71, -0.71],
       [ 0.  ,  0.  ,  0.71,  0.71]])

In [44]:
#Q5
L = np.array([[.1,.7,.1,.1],
              [.7,.1,.1,.1],
              [.1,.1,.1,.7],
              [.1,.1,.7,.1]])

vals, vecs = np.linalg.eig(L)
print(f"Autovalores: {np.real(vals).round(2)}")

order = np.absolute(vals).argsort()[::-1]
order
np.real(vecs).round(2)

Autovalores: [-0.6  0.6  1.  -0.6]


array([[ 0.71, -0.5 , -0.5 , -0.07],
       [-0.71, -0.5 , -0.5 ,  0.07],
       [-0.  ,  0.5 , -0.5 , -0.7 ],
       [ 0.  ,  0.5 , -0.5 ,  0.7 ]])

In [8]:
# Q9
A = np.array([[3/2, -1],
              [-1/2, 1/2]])

C = np.array([[1 - 3**(0.5), 1 + 3**(0.5)],
              [1, 1]])

Cinv = np.linalg.inv(C)

np.matmul(np.matmul(Cinv, A), C)

array([[ 1.28867513, -1.57735027],
       [-0.42264973,  0.71132487]])